### ISSUE TITLE
compiler dependency is out of date

### ISSUE THREAD

**Issue by EvanPurkhiser** [kaitai-io/kaitai-struct-loader#3]
Looks like this still points at `^0.7`, would be great to point at the latest compiler so we can have all the new features using this loader :)

**Comment by Ithamar** [comment]
This issue is actually fixed by #5 already now, as it updated the kaitai packages to 0.9.0

**Comment by generalmimon** [comment]
@Ithamar 
> This issue is actually fixed by #5 already now, as it updated the kaitai packages to 0.9.0

Yes, thanks.
